### PR TITLE
Added support for Test::Mojo::WithRoles

### PR DESCRIPTION
**Pull request by avkhozov**

### CODE REVIEW

**Comment by avkhozov** [comment]
@jberger, please give feedback.

**Comment by jberger** [comment]
It certainly can be done this way. An easier abstraction might be to move the logic to the role and then the subclass and just compose the role into the subclass. 

FWIW, I started working on my own role-based solution that was intended for sessions flashes and cookies (merging your work and Test::Mojo::More). The result (so far) is here: https://gist.github.com/jberger/72527a9702c2ed8b5e2f You would be welcome to borrow from it, if you like. I think the extraction code is a little safer. Also, I don't rely on _test, which is private.

**Comment by avkhozov** [comment]
Thanks!

Extracting a session from controller really is more simple and reliable way.

**Comment by jberger** [comment]
decided not to use the other logic then?

**Comment by avkhozov** [comment]
I decided to leave the logic in package Test::Mojo::Session, in order to dependence Role::Tiny was not required for my module.

Getting session using the controller I will add, but a little later today.

**Comment by jberger** [comment]
I guess that makes sense. I have kinda wondered if there will be a proliferation of parallel modules then, one role and one subclass. I have to admit it is attractive for certain reasons.

**Comment by avkhozov** [comment]
Hm, perhaps Test::Mojo::Session should not contain Test::Mojo::Role::Session?

**Comment by jberger** [comment]
No, IMO it should, forget what I said before. That was me just thinking about the future of Roles. I would rather encourage them.

**Comment by avkhozov** [comment]
Ok, thanks for discussing.

**Pull request merged**
